### ISSUE TITLE
Class 'CreateItemMetaTable' not found on migrate:rollback

### ISSUE THREAD

**Issue by ray1618** [phoenix-labs/eloquent-meta#14]
I created an Unique Meta Model and Table for my Items model.
I can migrate the models with no problem but when I try to migrate:rollback / migrate:reset I get the next error:
Class 'CreateItemMetaTable' not found.

It ain't fixed with composer dump-autoload, any idea how to fix this?

**Comment by chrismichaels84** [comment]
I'll look into this. May I assume that the table was item_meta?

**Comment by chrismichaels84** [comment]
I was only able to partially reproduce the bug. I also got a class not found error. But after I ran `composer dump-autoload` and then `php artisan migrate:rollback` it worked without any error. I've triple checked the migration file and its identical to the factory ones.

Could you tell me what version of Laravel you are using, and if you have made any modifications to the standard directory structure (like moved migrations out of /database/)? 

As a temporary work-around, you can add that class specifically to your autoloader in composer.json:
```js
"autoload": {
        "files": ["database/migrations/file_name_here.php"]
    }
```
but this really isn't a long term solution.

**Comment by ray1618** [comment]
Thnx I will check out if this removes the error tonight.

I use standard out of the box laravel5
Installed on a windows machine with XAMPP

**Comment by ray1618** [comment]
After I put the file in in the autoload array in composer.json it ran.
Now I commented it out for testing and it does migrate / migrate:refresh like normal. Seems like issue is fixed, tough I don't really understand why ;) But thanks for the help!

**Comment by chrismichaels84** [comment]
You got it.
